Update main.yml

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -16,3 +16,18 @@ jobs:
           azure-devops-project-url: 'https://dev.azure.com/prathambande/Playground'
           azure-pipeline-name: 'BuildSDK' # name of the Azure pipeline to be triggered
           azure-devops-token: '${{ secrets.AZURE_DEVOPS_TOKEN }}'
+
+      - name: Wait for Pipeline to Complete
+        uses: Azure/pipelines@v1
+        with:
+          azure-devops-project-url: 'https://dev.azure.com/prathambande/Playground'
+          azure-pipeline-name: 'BuildSDK' # Name of the Azure pipeline to be triggered
+          azure-devops-token: '${{ secrets.AZURE_DEVOPS_TOKEN }}'
+          wait-for-pipeline: true # Waits for the pipeline to complete
+
+      - name: Check Pipeline Result
+        run: |
+          if [[ "$(az pipelines build show --project Playground --id $(steps.trigger-pipeline.outputs.pipeline-id) --query result)" != "succeeded" ]]; then
+            echo "Pipeline failed"
+            exit 1
+          fi
